version: "3.4"
services:
  streamlit-multi-pages:
    tty: true
    image: "the-icaro/streamlit-multi-pages"
    stdin_open: true
    build:
      context: .
      target: "development"
    volumes:
      - ".:/app"
    networks:
      - db_nw

networks:
  db_nw:
    driver: bridge
